#H2 DataBase 설정
datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://ENC(o3IXzDM5TfCA/TMMFOI/vb3v6v8Px9ip9odMC0/BYk92ZO2iLSHuCg==)?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
  username: ENC(l0geYI6uhNgrVdoByJTOnQ==)             # MYSQL DB 접속 ID
  password: ENC(TaqxKoowZZiNQweWQveI10BEtDiFWxjA)     # H2 DB 접속 패스워드
logging:
  level:
    org:
      springframework:
        jdbc: debug             # jdbc 로그 설정

regexp:
  password: ^(?=.*[A-Z])(?=.*[a-z])(?=.*\d)(?=.*[\W]).{10,}$


schedules:
  cron-expression:
    publisher: 0 0 23 * * *


# websocket broker 설정
websocket:
  broker:
    topic: /topic
    queue: /queue
  app:
    destination:
      prefix: /app
  endpoint: /chats
