spring:
  #H2 DataBase 설정
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test_db     # H2 DB 연결 주소 (인메모리)
    #    url: 'jdbc:h2:~/test'     # H2 DB 연결 주소 (임베디드 모드)
    username: ENC(cC4XCWzInWFSQGRp/1THIg==)    # H2 DB 접속 ID
    password:                                  # H2 DB 접속 패스워드

  # H2 콘솔 설정
  h2:
    console:
      enabled: true             # H2 콘솔 사용 여부
      path: /h2-console         # H2 접속 경로
      settings:
        web-allow-others: true  # H2 외부 접속 허용 여부
  sql:
    init:
      mode: always
      schema-locations: classpath*:h2/schema.sql
      data-locations: classpath*:h2/data.sql

logging:
  level:
    org:
      springframework:
        jdbc: debug             # jdbc 로그 설정

schedules:
  cron-expression:
    publisher: 0 0 23 * * *

regexp:
  password: ^(?=.*[A-Z])(?=.*[a-z])(?=.*\d)(?=.*[\W]).{10,}$

# websocket broker 설정
websocket:
  broker:
    topic: /topic
    queue: /queue
  app:
    destination:
      prefix: /app
  endpoint: /chats

weather:
  advance-minutes: 10
