DROP TABLE IF EXISTS MEMBER;

CREATE TABLE MEMBER
(
    MEMBER_ID     BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMAIL         VARCHAR(100) NOT NULL,
    PASSWORD      VARCHAR(255) NOT NULL,
    MEMBER_STATUS VARCHAR(100) NOT NULL,
    JOIN_DATE     DATE         NOT NULL,
    LEAVE_DATE    DATE,
    CREATED_AT    TIMESTAMP    NOT NULL
);

DROP TABLE IF EXISTS VOTE;

CREATE TABLE VOTE
(
    VOTE_ID    BIGINT AUTO_INCREMENT PRIMARY KEY,
    VOTE_DATE  DATE      NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UNIQUE (VOTE_DATE)
);


DROP TABLE IF EXISTS VOTE_RECORD;

CREATE TABLE VOTE_RECORD
(
    VOTE_RECORD_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    VOTE_ID        BIGINT       NOT NULL,
    USER_ID        BIGINT       NOT NULL,
    VOTE_TYPE      VARCHAR(100) NOT NULL,
    IS_CANCELED    TINYINT      NOT NULL,
    CREATED_AT     TIMESTAMP    NOT NULL
);

DROP TABLE IF EXISTS LIVE_CHAT;

CREATE TABLE LIVE_CHAT
(
    LIVE_CHAT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    MEMBER_ID    BIGINT       NOT NULL,
    MESSAGE      VARCHAR(255) NOT NULL,
    DELETED_FLAG TINYINT NOT NULL,
    CREATED_AT   TIMESTAMP    NOT NULL
);


CREATE INDEX ix_email ON member (email);

DROP TABLE IF EXISTS WEATHER;

CREATE TABLE WEATHER
(
    WEATHER_ID        VARCHAR(10) NOT NULL PRIMARY KEY,
    LATITUDE          VARCHAR(50) NOT NULL,
    LONGITUDE         VARCHAR(50) NOT NULL,
    FORECAST_DATETIME TIMESTAMP   NOT NULL,
    TEMPERATURE DOUBLE NULL,
    RELATIVE_HUMIDITY INT NULL,
    RAINFALL DOUBLE NULL,
    SNOWFALL DOUBLE NULL,
    CREATED_AT        TIMESTAMP   NOT NULL
);


