DROP TABLE IF EXISTS VOTE;

CREATE TABLE VOTE
(
    VOTE_ID    BIGINT AUTO_INCREMENT PRIMARY KEY,
    VOTE_DATE  DATE      NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UNIQUE (VOTE_DATE)
);


DROP TABLE IF EXISTS VOTE_RECORD;

CREATE TABLE VOTE_RECORD
(
    VOTE_RECORD_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    VOTE_ID        BIGINT       NOT NULL,
    USER_ID        BIGINT       NOT NULL,
    VOTE_TYPE      VARCHAR(100) NOT NULL,
    IS_CANCELED    TINYINT      NOT NULL,
    CREATED_AT     TIMESTAMP    NOT NULL
);
