ALTER TABLE VOTE
    ALTER COLUMN VOTE_ID RESTART WITH 1; -- 시퀀스 초기화
TRUNCATE TABLE VOTE; -- 테이블 초기화 (테이블 스키마 유지)
ALTER TABLE VOTE_RECORD
    ALTER COLUMN VOTE_RECORD_ID RESTART WITH 1;
TRUNCATE TABLE VOTE_RECORD;
